const projects = [
  {
    id: 1,
    url: 'https://portfolio.mosalito.com/',
    img: '/projects/portfolio/portfolio.svg',
    title: 'Portfolio White',
    type: "Website",
    icon: "https://imgur.com/f0pqZyp.png",
  },
  {
    id: 2,
    url: 'https://shop.mosalito.com/',
    img: '/projects/portfolio/1.svg',
    title: 'Shop',
    type: "Website",
    icon: "/projects/portfolio/home.webp",
  },
  {
    id: 3,
    url: 'https://sibimpact.com/',
    img: '/projects/portfolio/2.svg',
    title: 'Sib Impact',
    type: "Website",
    icon: "/projects/playstation/icon.svg",
  },
  {
    id: 4,
    url: 'https://blog.greenmainframe.com/',
    img: '/projects/portfolio/3.svg',
    title: 'Green Mainframe Blog',
    type: "Website",
    icon: "/projects/podcastr/icon.svg",
  },
  {
    id: 5,
    url: 'https://beerwiththeboss.mosalito.com/',
    img: '/projects/portfolio/4.svg',
    title: 'Beer with the Boss',
    type: "Website",
    icon: "/projects/dsmeta/dsmeta-icon.svg",
  },
  {
    id: 6,
    url: 'https://projetos.mosalito.com/portfolio',
    img: '/projects/portfolio/5.svg',
    title: 'Landing Page',
    type: "Page",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 7,
    url: 'https://www.youtube.com/watch?v=Ztc-7unmgMA&t=2s',
    img: '/projects/portfolio/6.png',
    title: 'Logo Green Mainframe',
    type: "video",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 8,
    url: 'https://projetos.mosalito.com/landing1/',
    img: '/projects/portfolio/7.svg',
    title: 'Landing Page',
    type: "Page",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 9,
    url: 'https://projetos.mosalito.com/webera/',
    img: '/projects/portfolio/8.svg',
    title: 'Landing Page',
    type: "Page",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 10,
    url: 'https://webera.mosalito.com/',
    img: '/projects/portfolio/9.svg',
    title: 'Webera',
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 11,
    url: 'https://projetos.mosalito.com/',
    img: '/projects/portfolio/10.svg',
    title: 'Shop',
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 12,
    url: 'https://us.mototalk.com/new-site-mototalk/',
    img: '/projects/portfolio/11.svg',
    title: 'Mototalk',
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 13,
    url: 'https://projetos.mosalito.com/ilustracao4/',
    img: '/projects/portfolio/12.svg',
    title: 'Shop',
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
  },
  {
    id: 14,
    url: 'https://projetos.mosalito.com/ilustracao/',
    img: '/projects/portfolio/13.svg',
    title: 'Shop',
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
  }
]

export default projects